name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Gerar APK
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer -v android debug
          workdir: .

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: divulgador-produtos-apk
          path: bin/*.apk
